name: API CI/CD-DEV

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  trigger-cicd:
    uses: ./.github/workflows/generic-CICD.yaml
    with:
      docker_build_context: .
      environment: dev