name: API CI/CD-DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: 
      packages: write
      
jobs:
  trigger-cicd:
    uses: ./.github/workflows/generic-CICD.yaml
    with:
      environment: main